version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_thom}"
    image: localstack/localstack
    # network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=kenesis
      # - KINESIS_INITIALIZE_STREAMS=thom-stream:1
      - KENESIS_PORT_EXTERNAL=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=9000
      - START_WEB=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
